# Generated by Django 4.0.3 on 2022-04-21 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='images')),
                ('status', models.BooleanField(default=True, verbose_name='آیا نمایش داده شود')),
                ('position', models.IntegerField(verbose_name='پوزیشن')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='restaurant.category', verbose_name='زیر\u200cدسته')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم')),
                ('image', models.ImageField(upload_to='images', verbose_name='عکس')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('status', models.BooleanField(default=True, verbose_name='موجود')),
                ('price', models.FloatField(verbose_name='قیمت')),
                ('discount_price', models.FloatField(default=0, verbose_name='قیمت با تخفیف')),
                ('category', models.ManyToManyField(related_name='foods', to='restaurant.category', verbose_name='دسته\u200cبندی')),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to=settings.AUTH_USER_MODEL, verbose_name='آشپز')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='dislikes', to=settings.AUTH_USER_MODEL, verbose_name='دیس لایک')),
            ],
            options={
                'verbose_name': 'غذا',
                'verbose_name_plural': 'غذاها',
            },
        ),
        migrations.CreateModel(
            name='FoodHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.food')),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.ipaddress')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='hits',
            field=models.ManyToManyField(related_name='hits', through='restaurant.FoodHit', to='account.ipaddress', verbose_name='بازدید ها'),
        ),
        migrations.AddField(
            model_name='food',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='لایک'),
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان فرستادن')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sended_contact_messages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پیام ارسال شده برای پشتیبانی',
                'verbose_name_plural': 'پیام های ارسال شده برای پشتیبانی',
            },
        ),
        migrations.CreateModel(
            name='BookTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='تاریخ')),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=11, verbose_name='شماره تلفن')),
                ('guest', models.CharField(choices=[('1', 'یک نفر'), ('2', 'دو نفر'), ('3', 'سه نفر'), ('4', 'چهار نفر'), ('5', 'پنج نفر'), ('6', 'شیش نفر'), ('7', 'هفت نفر'), ('8', 'هشت نفر'), ('9', 'نه نفر'), ('10', 'ده نفر'), ('11', 'یازده نفر'), ('12', 'دوازده نفر'), ('13', 'سیزده نفر'), ('14', 'چهارده نفر'), ('15', 'پانزده نفر')], max_length=2, verbose_name='تعداد مهمان ها')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_tables', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش رزرو میز',
                'verbose_name_plural': 'سفارش ها برای رزرو میز',
            },
        ),
    ]
