# Generated by Django 4.0.3 on 2022-05-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='paid_time',
            field=models.DateTimeField(null=True, verbose_name='زمان پرداخت'),
        ),
    ]
