# Generated by Django 4.0.3 on 2022-05-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_paid_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='paid_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت'),
        ),
    ]
