# Generated by Django 4.0.3 on 2022-03-29 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_alter_comment_id_alter_flag_id_alter_flaginstance_id_and_more'),
        ('comment', '0012_blockeduser_blockeduserhistory'),
    ]

    operations = [
    ]
