# Generated by Django 4.0.3 on 2022-04-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=200, verbose_name='متن اصلی سایت')),
                ('homepage_thumbnail_text1', models.CharField(max_length=200, verbose_name='متن عکس صفحه\u200cی اصلی سایت شماره ۱')),
                ('homepage_thumbnail_text2', models.CharField(max_length=200, verbose_name='متن عکس صفحه\u200cی اصلی سایت شماره ۲')),
                ('homepage_thumbnail_text3', models.CharField(max_length=200, verbose_name='متن عکس صفحه\u200cی اصلی سایت شماره ۳')),
                ('homepage_thumbnail_description1', models.TextField(verbose_name='توضیحات عکس صفحه\u200cی اصلی سایت شماره ۱')),
                ('homepage_thumbnail_description2', models.TextField(verbose_name='توضیحات عکس صفحه\u200cی اصلی سایت شماره ۲')),
                ('homepage_thumbnail_description3', models.TextField(verbose_name='توضیحات عکس صفحه\u200cی اصلی سایت شماره ۳')),
                ('work_address', models.CharField(max_length=300, verbose_name='آدرس محل کار')),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=11, verbose_name='شماره تلفن')),
                ('email_address', models.EmailField(blank=True, max_length=254, verbose_name='آدرس ایمیل')),
                ('footer_text', models.TextField(verbose_name='متن فوتر')),
                ('twitter_address', models.URLField(verbose_name='آدرس اکانت تویتر')),
                ('youtube_address', models.URLField(verbose_name='آدرس اکانت یوتیوب')),
                ('instagram_address', models.URLField(verbose_name='آدرس اکانت اینستاگرام')),
                ('linkedin_address', models.URLField(verbose_name='آدرس اکانت لینکدین')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
